runtime: python27
threadsafe: yes
api_version: 1

# Google App Engine's cache default expiration time is 10 minutes. It's suitable for most Production
# scenarios, but a shorter TTL may be desired for Development and QA, as it allows us to see a fresh
# code in action just a minute after the deployment.
default_expiration: 60s

handlers:

# To enhance security, all http requests are redirected to their equivalent https addresses (secure: always).

# Assets are retrieved directly from their parent folder.
- url: /
  static_dir: dist/gbscloud-ui/index.html
  upload: dist/gbscloud-ui/index.html
- url: /
  static_dir:dist/gbscloud-ui




skip_files:
- ^(?!dist)
